version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: "secret"
       MYSQL_DATABASE: "inventory"
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   web:
     depends_on:
       - db
     build: ./bot/
     ports:
       - "8080:8080"
     restart: always
     environment:
       MYSQL_HOST: "root:secret@tcp(db:3306)/inventory"

   scraper:
     depends_on:
       - db
     build: ./scraper/         
     restart: always
     environment:
       MYSQL_HOST: db 


volumes:
    db_data: {}
